
astra_db:
  collection_name: "ecom_product_assistant_collection_three"

embedding_model:
  provider: "nvidia"
  model_name: "nvidia/llama-3.2-nemoretriever-300m-embed-v1"

retriever:
  top_k: 10

llm:
  groq:
    provider: "groq"
    model_name: "deepseek-r1-distill-llama-70b"
    temperature: 0
    max_output_tokens: 2048

  google:
    provider: "google"
    model_name: "gemini-2.0-flash"
    temperature: 0
    max_output_tokens: 2048
